### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by KhanRana** [KhanRana/gossip_restaurant#1]
As a **customer**, I can **signup** so that ***I can register with the site***

## Acceptance Criteria
- The user have the option to signup using a username, email address and password.
- The user can also signup by using social media accounts i.e. facebook and google 
- After successful signup, the customer should be redirected to the home page
- The customer should receive a successful/fail registration popup message on the screen 

## Tasks
- [ ] Create a sign up form and review HTML and CSS
- [ ] Update the form model to include social media accounts option
- [ ] Update the form model to include social media accounts
- [ ] Update the model to redirect the user to the home page on successful signup
- [ ] Keep the user on the signup form if the signup not successful
- [ ] Pop up success of failed signup messages
- [ ] Test the functionality
